data:
  test_size: 0.1
  train_size: 0.7
  val_size: 0.2

model:
  batch_size: 8
  bert_model_name: nlpaueb/legal-bert-base-uncased  # Changed this
  max_length: 512
  t5_model_name: t5-base

paths:
  app: ../app
  data: ../data
  data_processed: ../data/processed
  data_raw: ../data/raw
  logs: ../logs
  models: ../models
  models_bert: ../models/bert
  models_fine_tuning: ../models/fine_tuning
  models_t5: ../models/t5
  notebooks: ../notebooks
  scripts: ../scripts
  tests: ../tests

training:
  learning_rate: 2.0e-05
  num_epochs: 3
  warmup_steps: 500
  weight_decay: 0.01
