name: Deploy Legal NLP App to Azure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AZURE_CONTAINER_REGISTRY: acrlegalnlptoolkitxhpyytf4ph474
  CONTAINER_NAME: legal-nlp-app
  RESOURCE_GROUP: legal-nlp-rg
  APP_NAME: legal-nlp-toolkit

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        python -m pytest tests/ -v --tb=short
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Build and push Docker image
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io
        username: ${{ secrets.AZURE_ACR_USERNAME }}
        password: ${{ secrets.AZURE_ACR_PASSWORD }}
    
    # - name: Build and push image
    #   run: |
    #     docker build -t ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_NAME }}:${{ github.sha }} .
    #     docker push ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_NAME }}:${{ github.sha }}
    - name: Build and push image using Azure CLI
      run: |
        az acr build --registry ${{ env.AZURE_CONTAINER_REGISTRY }} --image legal-nlp-app:${{ github.sha }} --image legal-nlp-app:latest .

    # - name: Deploy to Azure Container Apps
    #   uses: azure/container-apps-deploy-action@v1
    #   with:
    #     appSourcePath: ${{ github.workspace }}
    #     acrName: ${{ env.AZURE_CONTAINER_REGISTRY }}
    #     containerName: ${{ env.CONTAINER_NAME }}
    #     resourceGroup: ${{ env.RESOURCE_GROUP }}
    #     imageToDeploy: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_NAME }}:${{ github.sha }}

    - name: Deploy to Azure Container Apps
      run: |
        az containerapp create --name ${{ env.APP_NAME }} \
          --resource-group ${{ env.RESOURCE_GROUP }} \
          --image ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_NAME }}:latest \
          --target-port 8501 \
          --ingress external \
          --cpu 1.0 \
          --memory 2Gi \
          --min-replicas 1 \
          --max-replicas 3

    - name: Get application URL
      run: |
        APP_URL=$(az containerapp show --name ${{ env.APP_NAME }} --resource-group ${{ env.RESOURCE_GROUP }} --query "properties.configuration.ingress.fqdn" --output tsv)
        echo "Application deployed at: https://$APP_URL"